export const ENDPOINTS = {
    GET_PROPERTY_DETAILS: (propertyId) => `/api/properties/${propertyId}/details`,
    CREATE_PROPERTY_BASE: '/api/properties',
    GET_PROPERTIES: '/api/properties',
    CREATE_PROPERTY: '/api/properties/whole',
    GET_PRESIGNED_URL: '/api/images/presigned-url',
    DELETE_IMAGE: (imageId) => `/api/images/${imageId}`,
    GET_IMAGE: (imageId) => `/api/images/${imageId}`,
    CREATE_ROOM: (propertyId) => `/api/properties/${propertyId}/rooms`,
    GET_ROOMS: (propertyId) => `/api/properties/${propertyId}/rooms`,
    CREATE_PRODUCT: (roomId) => `/api/rooms/${roomId}/products`,
    COMPLETE_IMAGE_UPLOAD: (imageId) => `/api/images/${imageId}/complete`,
    CREATE_PRODUCT_SPECIFICATION: (productId) => `/api/products/${productId}/specifications`,
    CREATE_PRODUCT_DIMENSION: (productId) => `/api/products/${productId}/dimensions`,
    GET_PROPERTY: (propertyId) => `/api/properties/${propertyId}`,
    GET_ROOM: (roomId) => `/api/rooms/${roomId}`,
    GET_PRODUCTS: '/api/products',
    GET_PRODUCT: (productId) => `/api/products/${productId}`,
    GET_PRODUCT_DETAILS: (productId) => `/api/products/${productId}/details`,
    GET_IMAGES: '/api/images',
    USER: {
        ME: '/api/users/me',
        SELLER: '/api/users/me/seller',
    },
    UPDATE_PROPERTY: (propertyId) => `/api/properties/${propertyId}`,
    DELETE_PROPERTY: (propertyId) => `/api/properties/${propertyId}`,
    UPDATE_ROOM: (roomId) => `/api/rooms/${roomId}`,
    DELETE_ROOM: (roomId) => `/api/rooms/${roomId}`,
    UPDATE_PRODUCT: (productId) => `/api/products/${productId}`,
    DELETE_PRODUCT: (productId) => `/api/products/${productId}`,
    UPDATE_PRODUCT_SPECIFICATIONS: (productId) => `/api/products/${productId}/specifications`,
    UPDATE_PRODUCT_DIMENSIONS: (productId) => `/api/products/${productId}/dimensions`,
    DELETE_PRODUCT_SPECIFICATION: (specId) => `/api/products/specifications/${specId}`,
    DELETE_PRODUCT_DIMENSION: (dimensionId) => `/api/products/dimensions/${dimensionId}`,
};